services:
  postgres-db:
    image: postgres:16-alpine
    container_name: clinic-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: Vito
    ports:
      - "5433:5432"
    volumes:
      - clinic_pg_data:/var/lib/postgresql/data
    networks:
      - clinic-network

  auth-service:
    build:
      context: ./backend/auth-service
    container_name: clinic-auth-service
    restart: on-failure
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/Vito
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - postgres-db
    networks:
      - clinic-network

  medical-service:
    build:
      context: ./backend/medical-service
    container_name: clinic-medical-service
    restart: on-failure
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/Vito
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - postgres-db
    networks:
      - clinic-network

  frontend:
    build:
      context: ./frontend
    container_name: clinic-frontend
    restart: on-failure
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - medical-service
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  clinic_pg_data: